### PR TITLE
correction the home page

### PR DESCRIPTION
**Pull request by BajalanIman**
There was a bug on the home page with the replication of data. I've resolved this bug in this ticket.
image

### CODE REVIEW

**Comment by 006080** [comment]
Sorry, Iman, but it seems you are not taking into consideration the work done by other people. Can you see a Share Icon in the right corner? When clicked, it should open a Share Popup modal. The Carousel icon also has functionality. I am really tired of making corrections to it every time. Please pay attention to the contributions of other collaborators. Thanks!

**Comment by BajalanIman** [comment]
@006080 Maybe I didn't still get the point correctly, but what I can see in the main branch right now is this:

image

Also, by clicking the image, we should jump to the product page, but it's not working.

**Comment by 006080** [comment]
https://github.com/ReDI-School/F24-Berlin-Web-Circle/pull/241
Can you see this ticket that is waiting to be approved?

**Comment by 006080** [comment]
I was hurrying fixing it this time, because we have a demo tonight. It is bringing us to the ProductPage clicking on Title, Hosl, Price.

**Pull request closed without merging**
