### PR TITLE
Bug/move product page components

### PR DESCRIPTION
**Pull request by dvnishshanka**
Move Product Page components in Home to Product page.
Add styling to make sure the footer is at the bottom of the page

### CODE REVIEW

**Review by Konzisam — CHANGES_REQUESTED** [review]
The product page components are all moved to the product page as required.

There are some conflicts to resolve though, check on that. Otherwise it would be ready for a merge

**Comment by dvnishshanka** [comment]
Resolved the merge conflicts.

**Comment by dvnishshanka** [comment]
In this PR I have fixed the footer to the bottom,
Removed the unwanted code in the home page.
Moved all Product page components from home.

**Review by BhagyaPrasadSamarathunga — APPROVED** [review]
Looks nice need to address px to rem convert changes.

**Pull request merged**
