### PR TITLE
Feature/add category filter

### PR DESCRIPTION
**Pull request by dvnishshanka**
In the home page results are filtered if a category is selected.
image

I have restructured the same back end code used for search panel filtration and extended the same for category filtration as well.

In the filtered page, the user is able to further filter the result according to the category now.
When selected USA,
image

When used USA and Tiny Homes category
image

### CODE REVIEW

**Review by grabinskij — APPROVED** [review]
Awesome job! Destination and Categories are working perfectly! 🎉😊

**Comment by grabinskij** [comment]
Hi @Vidushani Nishshanka! I’ve approved Feature/add category filter #301. Just one suggestion: if you haven’t already planned this for another ticket, consider adding a message like "There are no destinations under this category" when no category is selected. This will help avoid an empty page. Alternatively, you could assign some destinations to every category.

**Comment by dvnishshanka** [comment]
@grabinskij Thank you for your suggestion. I will add a msg when there is no matching results.

**Comment by grabinskij** [comment]
> @grabinskij Thank you for your suggestion. I will add a msg when there is no matching results.

You are welcome🙂

**Pull request merged**
