### PR TITLE
Refactor/reservation card

### PR DESCRIPTION
**Pull request by grabinskij**
This pull request includes a partial refactor of the ReservationCard component. I have made it dynamic by implementing date calculations for reservations and conditionally changing the data and styling. I have also added some additional information and calculations to the AddGuestsPopUp and Guest components. The logic has been split into several components, including DatePicker, GuestCountDisplay, ReservationDatesSelector, WarningMessage, as well as some utility functions and hooks. Additionally, I have created validation for the input fields.

In the next steps, I or someone else will create the Calendar component and implement it once completed. When the Calendar is integrated into the ReservationDatesSelector, I will also fix the styles in conjunction with the Calendar and add the form submission logic.

I have also created  popups for ReservationDatesSelector and AddGuestsPopUp components.

Furthermore, I have created a mock JSON server that provides all the data for the ProductPage when the page is opened, and I have adjusted the props to retrieve all the data from the server.

<br>
<br>
<br>

**After opening, the checkout date is disabled:**
createDateSelector

<br>
<br>
<br>

**If the check-in date passes validation and exists, the checkout input will open:**
addCalculations

<br>
<br>
<br>

**Errors:**
errorHandling2
error2
error3
error4
min-stay-error

<br>
<br>
<br>

**The number of nights and the period are synchronized with the entered check-in and checkout dates:**
dynamic-dates-sync

<br>
<br>
<br>

**The types and count of guests are synchronized while increasing or decreasing the count of a certain type of guest:**
addGuestTypeCount

<br>
<br>
<br>

**Adults and children are counted together as guests, similar to the original Airbnb. The plus and minus buttons become disabled if the number of guests reaches the minimum and maximum allowed limits.**
guestMaxCount
**This is the allowed number of guests:**
allowedNumberOfGuests

<br>
<br>
<br>

**View without check-in and check-out dates:**
bottom-title

<br>
<br>
<br>

**If we have all the necessary data, the button changes from 'Check Availability' to 'Reserve' and allows submitting:**
readyForReservation

<br>
<br>
<br>

**View if everything was sold out**
soldout

<br>
<br>
<br>

**View from the animal service popup**
guestPopUp

<br>
<br>
<br>

**View from the shortcuts popup**
shortcutsPopUp

<br>
<br>
<br>

** Host section is dynamic by fetching host data from the backend, that I have created for testing purpose:**
host2

<br>

host1

### CODE REVIEW

**Comment by Konzisam** [comment]
Also no need for creating mock.server , as the backend team already has one. You could prepare the json and uselike **json-server** for testing specific things..

**Comment by grabinskij** [comment]
> Hello @grabinskij while I can see your changes are phenomenal, making 49 changes in one branch is abit too much. It makes it so hard to review, now unfortunately the branch is getting outdated yet you had so good additions!
> 
> solution, in my opinion to reduce chances of introducing bugs in main, would need to discuss on all the changes to see how they affect the exisitng code.probably on a call. Let me know what you think.

I agree that having too many changes in one branch is problematic. It was my mistake for forgetting to create a new branch while I had a lot of changes to implement. As a result, I decided to proceed with this branch for the rest of the code.
While splitting it up now might be too late without causing additional work, I'm unsure how to do it effectively. I believe this is something we should discuss further.

**Comment by grabinskij** [comment]
> Also no need for creating mock.server , as the backend team already has one. You could prepare the json and uselike **json-server** for testing specific things..

I created this mock server to ensure that all data could come from the server and to prepare the Product Page to receive data from it. I have already created JSON files containing all the data we need for the Product Page, and it now works I think — all data is being fetched successfully from the mock server.

We can copy and paste the implementation from the mock server to the real one and then delete the mock server. Alternatively, if there are already endpoints and JSON files for the Product Page, we can simply remove the mock server.

**Comment by Konzisam** [comment]
Would be suggest we review together on a call. Then we see what to remove and what to keep.

**Pull request closed without merging**
