### PR TITLE
266 categories carousel scroll

### PR DESCRIPTION
**Pull request by 006080**
Ok. I also made a fast improvement. Please, take a look at it.

### CODE REVIEW

**Comment by grabinskij** [comment]
> Ok. I also made a fast improvement. Please, take a look at it.

Good job! Your solution greatly improved the user experience :+1: I have left also my thoughts in the Slack.

**Comment by 006080** [comment]
Ok. I added some corrections. Waiting for approval)

**Comment by grabinskij** [comment]
> Ok. I added some corrections. Waiting for approval)

It looks greate :+1:

**Review by grabinskij — APPROVED** [review]
CategoryTabs looks very good. Good job :rocket:

**Pull request merged**
