### PR TITLE
Create header-user-menu

### PR DESCRIPTION
**Pull request by Sci-mo**
#79 This creates the header-user-menue

### CODE REVIEW

**Comment by GabrielMelhem** [comment]
Hey Samuel, 

i went through your branch and pull the code to my local repo. 
 - you are not calling the component anywhere so I ouldn't check the result because what i got was 
 
Screenshot 2024-10-01 at 16 24 31

**Comment by Sci-mo** [comment]
Hi Gabriel,
Yes, you are right, I will call it in the root or app.

**Comment by Sci-mo** [comment]
Hi Miklesch,
I will check the code again and will provide another new ticket.
Thanks

**Comment by Konzisam** [comment]
kindly, the component HeaderUser is logging some errors in main:
image

**Comment by miklesch** [comment]
Have you done a new pull from main?Because there was an issue with node modules. But it should be solved now.On my computer it’s working…Von meinem Mobiltelefon gesendetAm 17.10.2024 um 22:57 schrieb Samuel Konzi ***@***.***>:﻿
kindly, the component HeaderUser is logging some errors in main:
image.png (view on web)

**Comment by Konzisam** [comment]
just pulled and its still there. check the component HEaserUserMenu.jsx. I wonder if any other person has the error

**Comment by miklesch** [comment]
I am getting the same error. If i put "aria-expand" to the button, then it´s working.

**Pull request closed without merging**
